version: "3.8"
services:
  api_service:
    container_name: spring-time-fun-webservices
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true    
    depends_on:
      - mysqldb    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    container_name: mysqldb
    image: "mysql:8.2"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: spring_time_fun
#      MYSQL_USER: amila_one
#      MYSQL_PASSWORD: Amila_pw
      MYSQL_ROOT_PASSWORD: root
networks:
  springapimysql-net: